from pathlib import Path
import json,subprocess,hashlib,csv
D=Path(__file__).resolve().parent;R=D/'adapters/baseline';O=R/'load-parity';O.mkdir(exist_ok=True);P=json.loads((R/'build_provenance.json').read_text());S=Path(P['source']);B=Path(P['build_dir'])
r=(R/'body-benchmark/renderer_body.cpp').read_text();x=(D/'mesh_exact_readback.inc').read_text().replace('lastExactDump=dump;updatePartPoses(fp);','lastExactDump=dump;');start=x.index('        const auto&O=poseOwner[0]');end=x.index('        printf("REVIEW_EXACT_READBACK',start);x=x[:start]+x[end:];anchor='  return; // Diagnostic load/upload-only:';assert r.count(anchor)==1;r=r.replace(anchor,x+'\n'+anchor);(O/'renderer.cpp').write_text(r)
h=(R/'body-benchmark/main.cpp').read_text().replace('if(argc!=3)','if(argc!=4)');anchor='  g_ren.renderScene(fp,{},{});';h=h.replace(anchor,'  const auto dir=std::string(argv[3])+"/"+std::to_string(model);std::filesystem::create_directories(dir);const auto dump=dir+"/body"+(slot?"_cockpit":"_outside")+"_geometry.csv";setenv("REVIEW_MESH_DUMP",dump.c_str(),1);\n'+anchor);(O/'main.cpp').write_text(h)
flags=['g++','-std=c++17','-O2','-DNDEBUG','-I'+str(S/'src'),'-I'+str(B/'gen')];subprocess.run(flags+['-c',str(O/'renderer.cpp'),'-o',str(O/'renderer.o')],check=True);subprocess.run(flags+[str(O/'main.cpp'),str(S/'src/radio_stub.cpp'),str(O/'renderer.o')]+P['linked_objects']+['-ldl','-pthread','-o',str(O/'load_parity')],check=True)
(O/'provenance.json').write_text(json.dumps({'baseline_visual_adapter':P['binary_sha256'],'binary_sha256':hashlib.sha256((O/'load_parity').read_bytes()).hexdigest(),'renderer_sha256':hashlib.sha256((O/'renderer.cpp').read_bytes()).hexdigest(),'main_sha256':hashlib.sha256((O/'main.cpp').read_bytes()).hexdigest(),'change':'Same original production load/upload with read-only exact GPU static/part/hull capture; no pose/display/scene shader compilation. This is not the timed benchmark binary.'},indent=2)+'\n')
out=D/'baseline-local-loaded';out.mkdir(exist_ok=True)
for row in csv.DictReader((D/'baseline-identities/identities.csv').open()):
 f=out/row['model'];f.mkdir(exist_ok=True);(f/('body_'+('cockpit' if row['slot']=='1' else 'outside')+'_geometry.csv.cache.txt')).write_text(str(D/'baseline-cache'/row['cache_name'])+'\n')
