#!/usr/bin/env python3
from pathlib import Path
import argparse,json,re,hashlib
p=argparse.ArgumentParser();p.add_argument('run',type=Path);p.add_argument('--report',type=Path,required=True);a=p.parse_args();phases=[]
for path in sorted(a.run.glob('*/render_*.log')):
 t=path.read_text();model=int(path.parent.name);phase=path.stem[7:]
 bodies=[{'model':int(m),'slot':int(s),'seconds':float(sec),'shader_hits':int(h),'shader_misses':int(ms),'built_count':int(b)} for m,s,sec,h,ms,b in re.findall(r'REVIEW_BODY_END model=(\d+) slot=(\d+) seconds=([\d.]+) shader_hits=(\d+) shader_misses=(\d+) built=(\d+)',t)]
 shaders=[{'seconds':float(sec),'hits':int(h),'misses':int(m),'stage':name} for sec,h,m,name in re.findall(r'REVIEW_SHADER seconds=([\d.]+) hits=(\d+) misses=(\d+) stage=([^\n]*)',t)]
 cache=re.findall(r'CACHE shader_hits=(\d+) shader_misses=(\d+) meshes_requested=(\d+) meshes_built=(\d+)',t)
 package=re.findall(r'REVIEW_PREBUILT hits=(\d+) misses=(\d+)',t)
 errors=[x for x in re.findall(r'FRAME \S+ \d+ [\d.]+s GL([0-9a-f]+)',t) if x!='0']
 entry={'model':model,'phase':phase,'log':str(path),'log_sha256':hashlib.sha256(path.read_bytes()).hexdigest(),'world_seconds':[float(x) for x in re.findall(r'REVIEW_WORLD_SECONDS ([\d.]+)',t)],'init_seconds':[float(x) for x in re.findall(r'REVIEW_INIT_SECONDS ([\d.]+)',t)],'bodies':bodies,'shader_stages':shaders,'cockpit_display_shader_seconds':sum(x['seconds'] for x in shaders if x['stage']=='cockpit displays'),'builder_shader_seconds':sum(x['seconds'] for x in shaders if x['stage'].startswith('aircraft bake')),'all_shader_seconds':sum(x['seconds'] for x in shaders),'frames':len(re.findall(r'^FRAME ',t,re.M)),'saved_images':len(re.findall(r'^SAVED ',t,re.M)),'gl_errors':errors,'cache_counters':dict(zip(['shader_hits','shader_misses','meshes_requested','meshes_built'],map(int,cache[-1]))) if cache else None,'package_counters':dict(zip(['hits','misses'],map(int,package[-1]))) if package else None,'unsafe_shader_notes':any(x in t for x in ["built without the retractable gear","every aircraft) failed","DIAGNOSTIC mesh unavailable"])}
 phases.append(entry)
r={'run':str(a.run),'backend':'EGL llvmpipe software renderer','limits':'No RTX 3070 or hardware FPS guarantee. Shader stage timers include cache lookup/pruning/link work. Body timer includes load/bake/upload; builder shader time is reported separately and overlaps the body timer. First-run world and display shaders are unrelated costs.','phases':phases,'body_count':sum(len(x['bodies']) for x in phases),'body_seconds':sum(b['seconds'] for x in phases for b in x['bodies']),'images':sum(x['saved_images'] for x in phases),'frames':sum(x['frames'] for x in phases),'all_gl_errors_zero':all(not x['gl_errors'] for x in phases),'no_unsafe_shader_notes':all(not x['unsafe_shader_notes'] for x in phases),'display_shader_seconds':sum(x['cockpit_display_shader_seconds'] for x in phases),'meshes_built':sum(x['cache_counters']['meshes_built'] for x in phases if x['cache_counters'])}
a.report.parent.mkdir(parents=True,exist_ok=True);a.report.write_text(json.dumps(r,indent=2)+'\n');print(json.dumps({k:v for k,v in r.items() if k not in ['phases','limits']},indent=2))
