# Generates src/font_data.h: a signed-distance-field glyph atlas (ASCII 32..126)
# from DejaVu Sans Bold (Bitstream Vera license, free to embed).
import sys, numpy as np
from PIL import Image, ImageDraw, ImageFont
from scipy import ndimage
FONT = sys.argv[1] if len(sys.argv) > 1 else "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
OUT = sys.argv[2] if len(sys.argv) > 2 else "src/font_data.h"
SZ, PAD, SS = 40, 5, 4          # em size in atlas px, padding, supersample
SPREAD = 5.0
font = ImageFont.truetype(FONT, SZ * SS)
asc, desc = font.getmetrics()
lineh = (asc + desc) / SS
cellw, cellh = 0, int(np.ceil(lineh)) + 2 * PAD
chars = [chr(c) for c in range(32, 127)]
adv = {c: font.getlength(c) / SS for c in chars}
cellw = int(np.ceil(max(adv.values()))) + 2 * PAD + 4
cols = 16
rows = (len(chars) + cols - 1) // cols
W, H = cols * cellw, rows * cellh
atlas = np.zeros((H, W), np.uint8)
meta = []
for i, c in enumerate(chars):
    cx, cy = (i % cols) * cellw, (i // cols) * cellh
    img = Image.new("L", (cellw * SS, cellh * SS), 0)
    ImageDraw.Draw(img).text((PAD * SS, PAD * SS), c, font=font, fill=255)
    a = np.array(img) > 127
    din = ndimage.distance_transform_edt(a)
    dout = ndimage.distance_transform_edt(~a)
    sd = (dout - din) / SS  # positive outside
    sd = sd.reshape(cellh, SS, cellw, SS).mean(axis=(1, 3))
    v = np.clip(0.5 - sd / (2 * SPREAD), 0, 1)
    atlas[cy:cy + cellh, cx:cx + cellw] = (v * 255).astype(np.uint8)
    meta.append((cx, cy, adv[c]))
# RLE-free: emit as compact string literal of hex is big; use base-85-ish via raw bytes in octal-safe array
with open(OUT, "w") as f:
    f.write("// Generated by tools/gen_font.py from DejaVu Sans Bold (Bitstream Vera license).\n#pragma once\n")
    f.write(f"static const int FONT_W={W}, FONT_H={H}, FONT_CELLW={cellw}, FONT_CELLH={cellh}, FONT_PAD={PAD}, FONT_EM={SZ};\n")
    f.write(f"static const float FONT_LINEH={lineh:.3f}f, FONT_ASC={asc/SS:.3f}f, FONT_SPREAD={SPREAD}f;\n")
    f.write("static const float FONT_ADV[95]={" + ",".join(f"{m[2]:.2f}f" for m in meta) + "};\n")
    f.write("static const unsigned char FONT_PIX[] = {\n")
    flat = atlas.flatten()
    for j in range(0, len(flat), 40):
        f.write(",".join(str(x) for x in flat[j:j + 40]) + ",\n")
    f.write("};\n")
print(W, H, cellw, cellh)
