#!/usr/bin/env python3
"""Generate the small shared GPU cockpit-layout table from reviewed model data."""
import argparse, json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
p = argparse.ArgumentParser(); p.add_argument('--check', action='store_true'); a = p.parse_args()
data = json.loads((ROOT/'assets/cockpits/layouts.json').read_text())
fields = ['pilot', 'copilot', 'systems', 'status', 'structure', 'controls', 'pedestal', 'trim', 'cloth']
def v4(v):
    assert len(v)==4
    return 'vec4(' + ','.join(f'{float(x):.4f}' for x in v) + ')'
out = '''//! kCockpitLayout
//! Generated by tools/generate_cockpit_layouts.py from assets/cockpits/layouts.json.
//! One bounded explicit model-indexed layout record drives physical housings, live atlas mapping,
//! glare deck, console geometry, moving-control mounts, and materials. No extra display targets.
// uModelId is uploaded in setRT for live and bake passes. Layout source participates in both
// shader and geometry-cache fingerprints; interior cache keys also include the model identity.
struct CockpitLayout {
  vec4 pilot, copilot; // body x, drop below eye, offset aft of packed panel, instrument scale
  vec4 systems;       // body x, drop below eye, offset aft of panel, engine/fuel scale
  vec4 status;        // body x, drop below eye, offset aft of panel, half width (half height = .70*w)
  vec4 structure;     // hood drop below eye, edge radius, chamfer depth, backing-bridge half height
  vec4 controls;      // primary-control drop/station from panel; push-pull x/drop (trainer x is mirrored)
  vec4 pedestal;     // half width, half height, half length, station shift from original center
  vec4 trim, cloth;   // cabin trim rgb / accent strength; upholstery rgb / leather mix
};
uniform vec4 uCockpitLayout[9]; // one selected model record, uploaded for live and bake passes
'''
records = {item['model']: item for item in data['aircraft']}
assert len(records) == len(data['aircraft']) and max(records) == 14
header = "// Generated by tools/generate_cockpit_layouts.py; do not edit.\n#pragma once\nstruct CockpitLayoutData { float value[9][4]; };\ninline constexpr CockpitLayoutData kCockpitLayouts[15] = {\n"
for i in range(15):
    item = records.get(i, dict(name='Dedicated research interior', **{field: [0,0,0,0] for field in fields}))
    header += f"  // {i}: {item['name']}\n  {{{{"
    header += ','.join('{'+','.join(f'{float(v):.4f}f' for v in item[field])+'}' for field in fields)
    header += '}}' + (',' if i<14 else '') + '\n'
header += '};\n'
out += '''
#if HAS_FLEET_CABIN
bool fleetCabin(){ return (gModelId >= 0 && gModelId < 10) || MODEL_IS(13) || MODEL_IS(14); }
#else
bool fleetCabin(){ return false; }
#endif
CockpitLayout cockpitLayout(){ return CockpitLayout(uCockpitLayout[0],uCockpitLayout[1],uCockpitLayout[2],uCockpitLayout[3],uCockpitLayout[4],uCockpitLayout[5],uCockpitLayout[6],uCockpitLayout[7],uCockpitLayout[8]); }
bool cockpitGlass(){ return int(gM[21].z + .5) == 2; }
bool cockpitTwin(){ return MODEL_IS(3) || MODEL_IS(8) || cockpitGlass(); }
vec2 cockpitFlightHalf(float scale){ return (cockpitGlass()?vec2(.184,.092):vec2(.147,.099))*scale; }
vec2 cockpitSystemsHalf(float scale){ return (cockpitGlass()?vec2(.105,.094):vec2(cockpitTwin()?.087:.052,.096))*scale; }
vec3 cockpitMount(vec4 m){ return vec3(m.x,gM[22].y-m.y,gM[21].w+m.z); }
vec3 cockpitYokeMount(float side){ CockpitLayout L=cockpitLayout(); return vec3(side*abs(gM[22].x),gM[22].y-L.controls.x,gM[21].w+L.controls.y); }
'''
destinations={ROOT/'src/shaders/cockpit_layout.glsl':out,ROOT/'src/cockpit_layout_data.h':header}
for dest,value in destinations.items():
    if a.check:
        if not dest.exists() or dest.read_text()!=value: raise SystemExit(f'{dest.name} is stale. Run tools/generate_cockpit_layouts.py')
    else: dest.write_text(value)
if a.check: print('PASS: bounded cockpit layout upload and CPU records match authored data')
