# Run with cmake -DSRC_DIR=<repository> -DOUT=<gen/header.h> -P <this file>.
# Identity is SHA256 of a schema prefix followed by sorted `path:sha256\n` records.
# CPU identity is used with runtime pruned GLSL; full identity certifies exporter input.
if(NOT DEFINED SRC_DIR OR NOT DEFINED OUT)
  message(FATAL_ERROR "SRC_DIR and OUT are required")
endif()
get_filename_component(SRC_DIR "${SRC_DIR}" ABSOLUTE)
set(CMAKE_SOURCE_DIR "${SRC_DIR}")
get_filename_component(OUT_DIR "${OUT}" DIRECTORY)
file(MAKE_DIRECTORY "${OUT_DIR}")
include("${SRC_DIR}/tools/aircraft_geometry_inputs.cmake")
file(GLOB SHADER_INPUTS "${SRC_DIR}/src/shaders/*.glsl")
list(SORT SHADER_INPUTS)
set(CPU_RECORDS "solace-aircraft-cpu-source-v1\n")
set(ALL_RECORDS "solace-aircraft-build-source-v1\n")
set(JSON_FILES "")
foreach(KIND cpu shader producer)
  if(KIND STREQUAL "cpu")
    set(INPUTS ${AIRCRAFT_GEOMETRY_CPU_INPUTS})
  elseif(KIND STREQUAL "shader")
    set(INPUTS ${SHADER_INPUTS})
  else()
    set(INPUTS ${AIRCRAFT_GEOMETRY_PRODUCER_INPUTS})
  endif()
  foreach(INPUT IN LISTS INPUTS)
    if(NOT EXISTS "${INPUT}")
      message(FATAL_ERROR "Missing aircraft geometry input: ${INPUT}")
    endif()
    file(RELATIVE_PATH RELATIVE "${SRC_DIR}" "${INPUT}")
    file(SHA256 "${INPUT}" HASH)
    if(KIND STREQUAL "cpu" OR KIND STREQUAL "producer")
      string(APPEND CPU_RECORDS "${RELATIVE}:${HASH}\n")
    endif()
    string(APPEND ALL_RECORDS "${RELATIVE}:${HASH}\n")
    if(NOT JSON_FILES STREQUAL "")
      string(APPEND JSON_FILES ",\n")
    endif()
    string(APPEND JSON_FILES "    {\"path\":\"${RELATIVE}\",\"sha256\":\"${HASH}\",\"kind\":\"${KIND}\"}")
  endforeach()
endforeach()
string(SHA256 CPU_DIGEST "${CPU_RECORDS}")
string(SHA256 BUILD_DIGEST "${ALL_RECORDS}")
file(WRITE "${OUT}.tmp" "// Generated source identities; do not edit.\n#pragma once\ninline constexpr char kAircraftGeometrySourceDigest[] = \"${CPU_DIGEST}\";\ninline constexpr char kAircraftBuildSourceDigest[] = \"${BUILD_DIGEST}\";\n")
configure_file("${OUT}.tmp" "${OUT}" COPYONLY)
file(REMOVE "${OUT}.tmp")
set(JSON_OUT "${OUT_DIR}/aircraft_geometry_source.json")
file(WRITE "${JSON_OUT}.tmp" "{\n  \"schema\":1,\n  \"digest\":\"${BUILD_DIGEST}\",\n  \"geometry_digest\":\"${CPU_DIGEST}\",\n  \"files\":[\n${JSON_FILES}\n  ]\n}\n")
configure_file("${JSON_OUT}.tmp" "${JSON_OUT}" COPYONLY)
file(REMOVE "${JSON_OUT}.tmp")
