#!/usr/bin/env python3
"""Solace Express - the night sky's stars: writes src/star_catalog.h from the Yale Bright Star Catalogue, 5th revised
edition (Hoffleit & Warren 1991; NASA ADC / CDS catalogue V/50, public domain), as published at
http://tdc-www.harvard.edu/catalogs/bsc5.dat.gz.

    python3 tools/generate_star_catalog.py bsc5.dat.gz src/star_catalog.h

Every star to visual magnitude 6.5 (what an eye sees on the darkest night): its right ascension and declination
(J2000), its visual magnitude and its B-V colour index, packed into four 16-bit numbers (20 arc-seconds, a hundredth of
a magnitude, a thousandth of B-V). The catalogue's fixed-width columns (its ReadMe): RA 76-83, Dec 84-90, V 103-107,
B-V 110-114. Entries without a position (the novae and clusters it keeps numbers for) are left out."""
import gzip, math, sys


def field(row, a, b):
    return row[a - 1:b].strip()


def main(src, out):
    opener = gzip.open if src.endswith('.gz') else open
    with opener(src, 'rt', encoding='latin-1') as f:
        rows = f.read().splitlines()
    stars = []
    for r in rows:
        if len(r) < 107 or not field(r, 76, 77) or not field(r, 103, 107):
            continue
        ra = (int(field(r, 76, 77)) + int(field(r, 78, 79)) / 60 + float(field(r, 80, 83)) / 3600) * 15.0
        dec = int(field(r, 85, 86)) + int(field(r, 87, 88)) / 60 + int(field(r, 89, 90)) / 3600
        if field(r, 84, 84) == '-':
            dec = -dec
        v = float(field(r, 103, 107))
        bv = float(field(r, 110, 114)) if field(r, 110, 114) else 0.6   # (a few lack a colour: a sun-like white)
        if v > 6.5:
            continue
        stars.append((v, ra, dec, bv))
    stars.sort()
    packed = []
    for v, ra, dec, bv in stars:
        packed.append((round(ra / 360.0 * 65535) % 65536, round((dec + 90.0) / 180.0 * 65535),
                       round((v + 2.0) * 100), round((max(-0.5, min(bv, 2.5)) + 0.5) * 1000)))
    with open(out, 'w', newline='\n') as f:
        f.write('// Generated by tools/generate_star_catalog.py from the Yale Bright Star Catalogue, 5th revised edition\n')
        f.write('// (Hoffleit & Warren 1991; NASA ADC / CDS V/50, public domain) - do not edit. Every star to magnitude 6.5,\n')
        f.write('// brightest first: right ascension (0..65535 round the sky, J2000), declination (0..65535 from the south pole\n')
        f.write('// to the north), visual magnitude + 2 in hundredths, B-V + 0.5 in thousandths.\n')
        f.write('#pragma once\n#include <cstdint>\n\n')
        f.write('static const int kStarCount = %d;\n' % len(packed))
        f.write('static const uint16_t kStarCatalog[][4] = {\n')
        for i in range(0, len(packed), 8):
            f.write('  ' + ' '.join('{%d,%d,%d,%d},' % s for s in packed[i:i + 8]) + '\n')
        f.write('};\n')
    print('%d stars to magnitude 6.5 -> %s' % (len(packed), out))


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2])
